import "./globals.css";
import { Inter } from "next/font/google";
import CartContextProvider from '../components/shoppingCart/CartProvider'
import { NextAuthProvider } from "./providers";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "amazona.com",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </head>
      <body className={inter.className}>
          
          <NextAuthProvider>
            <CartContextProvider>

            
            {children}</CartContextProvider>
            </NextAuthProvider>
      
      </body>
    </html>
  );
}
